## 应用名称
#spring.application.name=mongo_demo
## 应用服务 WEB 访问端口
#server.port=8080

spring:
  application:
    name: mongo_demo
  data:
    mongodb:
      host: 121.40.118.159
      database: test
      port: 27017
      #也可以使用uri连接 #uri: mongodb://192.168.40.134:27017/articledb
server:
  port: 8777
